"""user - add role

Revision ID: 5a253bea92a9
Revises: 77c90b43bb04
Create Date: 2025-09-21 12:26:46.709426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a253bea92a9'
down_revision: Union[str, Sequence[str], None] = '77c90b43bb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 먼저 nullable=True로 컬럼 추가
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=True))

    # 2. 기존 데이터에 기본값 설정
    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")

    # 3. 컬럼을 nullable=False로 변경
    op.alter_column('users', 'role',
                   existing_type=sa.String(length=32),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
